plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    api project(':lancet-base')
    api "org.ow2.asm:asm:$asm_version"
    api "org.ow2.asm:asm-tree:$asm_version"
    api "org.ow2.asm:asm-commons:$asm_version"
    api "org.ow2.asm:asm-util:$asm_version"
    api "com.google.guava:guava:$guava_version"

    compileOnly gradleApi()
    compileOnly "com.android.tools.build:gradle:$android_tools_version"

    testImplementation gradleApi()
    testImplementation "com.android.tools.build:gradle:$android_tools_version"
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.squareup.okio:okio:1.17.6'
    testImplementation 'org.assertj:assertj-core:3.24.2'
}
