plugins {
    id 'com.android.application' version '8.6.1'
    id 'org.jetbrains.kotlin.android' version '1.9.24'
    id 'me.ele.lancet'
}

def lancetSourceBuild = gradle.includedBuild('lancet')
def localLancetBase = files('../lancet-base/build/libs/lancet-base-1.0.7.jar')
localLancetBase.builtBy(lancetSourceBuild.task(':lancet-base:jar'))

def localLancetTestRuntime = files(
        '../lancet-weaver/build/libs/lancet-weaver-1.0.7.jar',
        '../lancet-plugin/build/libs/lancet-plugin-1.0.7.jar'
)
localLancetTestRuntime.builtBy(
        lancetSourceBuild.task(':lancet-weaver:jar'),
        lancetSourceBuild.task(':lancet-plugin:jar')
)

android {
    namespace 'com.sample.playground'
    compileSdk 34

    defaultConfig {
        applicationId 'com.sample.playground'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation localLancetBase

    testImplementation localLancetTestRuntime
    testImplementation gradleTestKit()
    testImplementation 'com.android.tools.build:gradle:8.6.1'
    testImplementation 'com.google.code.gson:gson:2.10.1'
    testImplementation 'com.google.guava:guava:33.0.0-jre'
    testImplementation 'org.ow2.asm:asm:9.6'
    testImplementation 'org.ow2.asm:asm-tree:9.6'
    testImplementation 'org.ow2.asm:asm-commons:9.6'
    testImplementation 'org.ow2.asm:asm-util:9.6'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.squareup.okio:okio:1.17.6'
    testImplementation 'org.assertj:assertj-core:3.24.2'
    testImplementation 'org.mockito:mockito-core:5.12.0'
}

tasks.register('executeTestSampleProduct', JavaExec) {
    mainClass = 'com.sample.playground.Main'
    classpath = files(layout.buildDirectory.dir('product/java/main')) +
            configurations.debugRuntimeClasspath
}

tasks.register('executeTestSample', JavaExec) {
    dependsOn 'compileDebugJavaWithJavac', 'compileDebugKotlin'
    mainClass = 'com.sample.playground.Main'
    classpath = files(layout.buildDirectory.dir(
            'intermediates/javac/debug/compileDebugJavaWithJavac/classes')) +
            files(layout.buildDirectory.dir('tmp/kotlin-classes/debug')) +
            configurations.debugRuntimeClasspath
}
