plugins {
    id 'java-gradle-plugin'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

gradlePlugin {
    plugins {
        lancet {
            id = 'me.ele.lancet'
            implementationClass = 'me.ele.lancet.plugin.LancetPlugin'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation "com.google.guava:guava:$guava_version"
    implementation project(':lancet-weaver')

    compileOnly "com.android.tools.build:gradle:$android_tools_version"

    testImplementation gradleTestKit()
    testImplementation "com.android.tools.build:gradle:$android_tools_version"
    testImplementation 'junit:junit:4.13.2'
}
